module(load="imudp")

# Listens for incoming Meraki logs on UDP 514
input(type="imudp" port="514")

# Forwards them directly to the Alloy container name over the internal network
*.* action(type="omfwd" 
           protocol="tcp" 
           target="alloy" 
           port="1514" 
           Template="RSYSLOG_SyslogProtocol23Format" 
           TCP_Framing="octet-counted" 
           KeepAlive="on")