module(load="imudp")

template(name="Meraki" type="string"
  string="<%PRI%>1 %timereported:::date-rfc3339% %fromhost-ip% meraki - - - %rawmsg%\n")

ruleset(name="forwardToAlloy") {
  action(
    type="omfwd"
    protocol="tcp"
    target="alloy"
    port="1514"
    Template="Meraki"
    TCP_Framing="octet-counted"
    KeepAlive="on"
  )
  stop
}

input(type="imudp" port="514" ruleset="forwardToAlloy")