services:
  syslog:
    image: rsyslog/rsyslog:latest
    container_name: syslog
    ports:
      - "514:514/udp"
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
    depends_on:
      - alloy