[global_tags]
  service = "snmp-traps"
  job = "snmp-traps"

[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "5s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true

[[inputs.snmp_trap]]
  service_address = "udp://:1162"

[[outputs.loki]]
  domain = "http://loki:3100"
  endpoint = "/loki/api/v1/push"
  metric_name_label = "metric"
  sanitize_label_names = true
