services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: "-target=all -config.file=/etc/config.yml"
    restart: always
    volumes:
      - ./config.yml:/etc/config.yml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP

volumes:
  tempo-data: